import React from 'react'

const TermsConditions = () => {
    return (
        <>
           <section id="header" className="d-flex align-items-center">
        <div className="container-fluid">
          <div className="row">
            <div className="col-10 mx-auto">
                <div className='row'>
              <div className="col-md-12  pt-lg-0 order-2 order-lg-1 d-flex flex-column">
              <h1 className=" techcare mb-3">TechCare • T & C</h1>
              <p> <strong>1. CONTRACTUAL RELATIONSHIP</strong></p>
                 <p>Terms These Terms of Use govern the access or use by you, an individual, from within India of applications, websites, content, products, and services made available by TechCare India Private Limited, a private limited company established in India.<br/>PLEASE READ THESE TERMS CAREFULLY BEFORE ACCESSING OR USING THE SERVICES.</p>
                 <p> Your access and use of the Services constitutes your agreement to be bound by these Terms, which establishes a contractual relationship between you and TechCare. If you do not agree to these Terms, you may not access or use the Services. These Terms expressly supersede prior written agreements with you.</p>
                 <p> Your access and use of the Services constitutes your agreement to be bound by these Terms, which establishes a contractual relationship between you and TechCare. If you do not agree to these Terms, you may not access or use the Services. These Terms expressly supersede prior written agreements with you.</p>
                 <p> TechCare may restrict you from accessing or using the Services, or any part of them, immediately, without notice, in circumstances where TechCare reasonably suspects that:</p>
                 <ul>
                     <li> you have, or are likely to, breach these Terms; and/or </li>
                 <li> you do not, or are likely not to, qualify, under applicable law or the standards and policies of TechCare and its affiliates, to access and use the Services. </li>
                 </ul>
                 <p> TechCare may terminate these Terms or any Services with respect to you, or generally cease offering or deny access to the Services or any portion thereof:</p>
<ul>
    <li> immediately, where TechCare reasonably suspects that: </li>
<ul>
    <li> you have, or are likely to, materially breach these Terms; and/or </li>
<li> you do not, or are likely not to, qualify, under applicable law or the standards and policies of TechCare and its affiliates, to access and use the Services; or </li>
</ul>
<li> on 30 days' written notice to you, where TechCare, acting reasonably, terminates these Terms or any Services for any legitimate business, legal or regulatory reason. </li>
</ul>
<p> Without limiting its other rights under these Terms, TechCare may immediately restrict or deactivate your access to the Services if you breach the Community Guidelines at any time.</p>
<p> You may terminate these Terms at any time, for any reason.</p>
<p> TechCare may amend the any policies or supplemental terms (including the Community Guidelines) related to the Services from time to time. TechCare will provide you with at least 30 days' written notice in the event of a material change to any policies or supplemental terms that detrimentally affects your rights under these Terms. Amendments will be effective upon TechCare’s posting of such amended policies or supplemental terms on the applicable Service. Your continued access or use of the Services after such posting, or after the expiry of the notice period (whichever is later), constitutes your consent to be bound by the Terms, as amended.</p>
<p> <strong>MODIFICATIONS TO TERMS OF USE AND/OR PRIVACY POLICY</strong></p>
<p> TechCare reserves the right, in its sole discretion, to change, modify, or otherwise amend the Terms, and any other documents incorporated by reference herein for complying with legal and regulatory framework and for other legitimate business purposes, at any time, and TechCare will post the amended Terms at the domain of www.TechCare.com/terms. It is your responsibility to review the Terms of Use for any changes and you areencouraged to check the Terms of Use frequently. Your use of the website (<a href="http://www.techcare.com">www.techcare.com</a>) (“ <strong>Website</strong>”) or Applications (as defined below) following the date that amendments to the Terms of Use take effect will signify your assent to and acceptance of any revised Terms of Use. If you do not agree to abide by these or any future Terms of Use, please do not use or access the UC Platform.</p>
<p> <strong>PRIVACY POLICY</strong></p>
<p> TechCare has established a Privacy Policy that explains to users how their personal information is collected and used.</p>
<p>The Privacy Policy is located at: <a href="https://www.urbanclap.com/privacy-policy">Privacy Policy</a>. The Privacy Policy contains information about how users may seek access to and correction of their personal information held by TechCare and how they may make a privacy complaint.</p>
<p> The Privacy Policy is hereby incorporated into the Terms of Use set forth herein. Your use of this Website and/ or the Applications is governed by the Privacy Policy.</p>
<p> TechCare may disclose users’ personal information to third parties. TechCare may provide to a claims processor or an insurer any necessary information (including your contact information) if there is a complaint, dispute or conflict, which may include an accident, involving you and a third party and such information or data is necessary to resolve the complaint, dispute or conflict. TechCare may also provide to a law enforcement agency, statutory body, governmental agency and/or investigative agency any necessary information (including your contact information) if required by law or in furtherance of any investigation involving you and a third party and such information or data is necessary towards the enquiry/investigation that is being carried out by the said body and/or agency as the case may be.</p>
<p> <strong>2. THE SERVICES</strong></p>
<p> TechCare will provide the Services to you under this Agreement. The Services constitute the provision of a technology platform that enablesyou, as a user of TechCare’s mobile application (each, an " <strong>Application</strong>") or Website to: (a) arrange and schedule home-based services with independent third party providers of thoseservices, who have an agreement with TechCare or its affiliates (“ <strong>Third Party Providers</strong>”); and (b) facilitate payments to Third Party Providers for the services and receive receipts for those payments.</p>
<p> The Services are made available solely for your personal, non-commercial use, unless TechCare has agreed with you otherwise in a separate agreement. You acknowledge that TechCare does not provide home-based services and that all such home-based services are provided by independent third party contractors who are not employed by TechCare or any of its affiliates. TechCare accepts liability for the Services and the UC Platform that it provides to you subject to these Terms. Third Party Providers are responsible for the services they provide to you.</p>
<p> <strong>License</strong> .</p>
<p> Subject to your compliance with these Terms, TechCare grants you a limited, non-exclusive, non-sublicensable, revocable, non-transferrable license to: (i) access and use the UC Platform on your personal device solely in connection with your use of the Services; and (ii) access and use any content, information and related materials that may be made available through the Services, in each case solely for your personal, non-commercial use. Any rights not expressly granted herein are reserved by TechCare and TechCare’s licensors.</p>
<p> <strong>Restrictions</strong> .</p>
<p> You may not: (i) remove any copyright, trademark or other proprietary notices from any portion of the Services; (ii) reproduce, modify, prepare derivative works based upon, distribute, license, lease, sell, resell, transfer, publicly display, publicly perform, transmit, stream, broadcast or otherwise exploit the Services except as expressly permitted by TechCare; (iii) decompile, reverse engineer or disassemble the Services except as may be permitted by applicable law; (iv) link to, mirror or frame any portion of the Services; (v) cause or launch any programs or scripts for the purpose of scraping, indexing, surveying, or otherwise data mining any portion of the Services or unduly burdening or hindering the operation and/or functionality of any aspect of the Services; or (vi) attempt to gain unauthorized access to or impair any aspect of the Services or its related systems or networks.</p>
<p> <strong></strong> <br/></p>
<p> <strong></strong> <br/></p>
<p> <strong>Provision of the Services.</strong></p>
<p> <strong></strong> <br/></p>
<p> You acknowledge that portions of the Services may be made available under TechCare’s various brands or request options. You also acknowledge that the Services may be made available under such brands or request options by or in connection with: (i) certain of TechCare’s subsidiaries and affiliates; or (ii) independent Third Party Providers.</p>
<p> <strong>Third Party Services and Content.</strong></p>
<p> The Services may be made available or accessed in connection with third party services and content (including advertising) that TechCare does not control. You acknowledge that different terms of use and privacy policies may apply to your use of such third party services and content. TechCare does not endorse such third party services and content and in no event shall TechCare be responsible or liable for any products or services of such third party providers. Additionally, Apple Inc., Google, Inc., Microsoft Corporation or BlackBerry Limited and/or their applicable international subsidiaries and affiliates will be third-party beneficiaries to this contract if you access the Services using Applications developed for Apple iOS, Android, Microsoft Windows, or Blackberry-powered mobile devices, respectively. These third party beneficiaries are not parties to this contract and are not responsible for the provision or support of the Services in any manner. Your access to the Services using these devices is subject to terms set forth in the applicable third party beneficiary’s terms of service.</p>
<p> <strong>Ownership</strong> .</p>
<p> The Services and all rights therein are and shall remain TechCare’s property or the property of TechCare’s licensors. Neither these Terms nor your use of the Services convey or grant to you any rights: (i) in or related to the Services except for the limited license granted above; or (ii) to use or reference in any manner TechCare’s company names, logos, product and service names, trademarks or services marks or those of TechCare’s licensors.</p>
<p> <strong>3. YOUR USE OF THE SERVICES</strong></p>
<p> <strong>User Accounts.</strong></p>
<p> In order to use most aspects of the Services, you must register for andmaintain an active personal user Services account (" <strong>Account</strong>"). You must be at least 18 years of age, or the age of legal majority in your jurisdiction (if different than 18), to obtain an Account, unless a specific Service permits otherwise. Account registration requires you to submit to TechCare certain personal information, such as your name, address, mobile phone number and age, as well as at least one valid payment method (either a credit card or accepted payment partner). You agree to maintain accurate, complete, and up-to-date information in your Account. Your failure to maintain accurate, complete, and up-to-date Account information, including having an invalid or expired payment method on file, may result in your inability to access or use the Services. You are responsible for all activity that occurs under your Account, and you agree to maintain the security and secrecy of your Account username and password at all times. Unless otherwise permitted by TechCare in writing, you may only possess one Account.</p>
<p> <strong>User Requirements and Conduct.</strong></p>
<p> The Service is not available for use by persons under the age of 18. You may not authorize third parties to use your Account, and you may not allow persons under the age of 18 to receive services from Third Party Providers unless they are accompanied by you. You may not assign or otherwise transfer your Account to any other person or entity. You agree to comply with all applicable laws when accessing or using the Services, and you may only access or use the Services for lawful purposes. You will not, in your use of the Services, cause nuisance, annoyance, inconvenience, or property damage, whether to the Third Party Provider or any other party. In certain instances you may be asked to provide proof of identity or other method of identity verification to access or use the Services, and you agree that you may be denied access to or use of the Services if you refuse to provide proof of identity or other method of identity verification.</p>
<p> <strong>No Discrimination.</strong></p>
<p> TechCare prohibits discrimination against Third Party Providers based on race, religion, caste, national origin, disability, sexual orientation, sex, marital status, gender identity, age or any other characteristic that may be protected under applicable law. Such discrimination includes, but is not limited to, any refusal to accept services based on any of these characteristics. If it is found that you have violated this prohibition you will lose access to the TechCare platform. Applicable laws in certain jurisdictions may require and/or allow the provision of services by and for the benefit of a specific category of persons. In such jurisdictions, services provided in compliance with these laws and the relevant applicable terms are permissible.</p>
<p> <strong>Text Messaging.</strong></p>
<p> By creating an Account, you agree that the Services may send you text (SMS) messages as part of the normal business operation of your use of the Services. You may opt-out of receiving text (SMS) messages from TechCare at any time by informing TechCare of your decision to stop receiving such text (SMS) messages. You acknowledge that opting out of receiving text (SMS) messages may impact your use of the Services.</p>
<p> <strong>Promotional Codes.</strong></p>
<p> TechCare may, in TechCare’s sole discretion, create promotional codes that may be redeemed for Account credit, or other features or benefits related to the Services and/or a Third Party Provider’s services, subject to any additional terms that TechCare establishes on a per promotional code basis ("<strong>Promo Codes</strong>"). You agree that Promo Codes: (i) must be used for the intended audience and purpose, and in a lawful manner; (ii) may not be duplicated, sold or transferred in any manner, or made available to the general public (whether posted to a public form or otherwise), unless expressly permitted by TechCare; (iii) may be disabled by TechCare at any time for any reason without liability to TechCare; (iv) may only be used pursuant to the specific terms that TechCare establishes for such Promo Code; (v) are not valid for cash; and (vi) may expire prior to your use. TechCare reserves the right to withhold or deduct credits or other features or benefits obtained through the use of Promo Codes by you or any other user in the event that TechCare reasonably determines or believes that the use or redemption of the Promo Code was in error, fraudulent, illegal, or in violation of the applicable Promo Code terms or these Terms.</p>
<p> <strong>User Provided Content.</strong></p>
<p> TechCare may, in TechCare’s sole discretion, permit you from time to time to submit, upload, publish or otherwise make available to TechCare through the Services textual, audio, and/or visual content and information, including commentary and feedback related to the Services, initiation of support requests, and submission of entries for competitions and promotions ("<strong>User Content</strong>"). Any User Content provided by you remains your property. However, by providing User Content to TechCare, you grant TechCare a worldwide, perpetual, irrevocable, transferable, royalty-free license, with the right to sublicense, to use, copy, modify, create derivative works of, distribute, publicly display, publicly perform, and otherwise exploit in any manner such User Content in all formats and distribution channels now known or hereafter devised (including in connection with the Services and TechCare’s business and on third-party sites and services), without further notice to or consent from you, and without the requirement of payment to you or any other person or entity.</p>
<p> You represent and warrant that: (i) you either are the sole and exclusive owner of all User Content or you have all rights, licenses, consents and releases necessary to grant TechCare the license to the User Content as set forth above; and (ii) neither the User Content nor your submission, uploading, publishing or otherwise making available of such User Content nor TechCare’s use of the User Content as permitted herein will infringe, misappropriate or violate a third party’s intellectual property or proprietary rights, or rights of publicity or privacy, or result in the violation of any applicable law or regulation; and (iii) you are not providing feedback for services performed by you in your capacity as a service provider on the platform.</p>
<p> You agree to not provide User Content that is defamatory, grossly harmful, blasphemous, paedophilic, invasive of another’s privacy, ethnically objectionable, disparaging, relating or encouraging money laundering of gambling, libelous, hateful, racist, violent, obscene, pornographic, unlawful, or otherwise offensive, as determined by TechCare in its sole discretion, whether or not such material may be protected by law. TechCare may, but shall not be obligated to, review, monitor, or remove User Content, at TechCare’s sole discretion and at any time and for any reason, without notice to you.</p>
<p> <strong>Network Access and Devices.</strong></p>
<p> You are responsible for obtaining the data network access necessary to use the Services. Your mobile network’s data and messaging rates and fees may apply if you access or use the Services from a wireless-enabled device and you shall be responsible for such rates and fees. You are responsible for acquiring and updating compatible hardware or devices necessary to access and use the Services and UC Platform and any updates thereto. TechCare does not guarantee that the Services, or any portion thereof, will function on any particular hardware or devices. In addition, the Services may be subject to malfunctions and delays inherent in the use of the Internet and electronic communications.</p>
<p> <strong>4. PAYMENT</strong></p>
<p> You understand that use of the Services may result in charges to you forthe services you receive from a Third Party Provider (" <strong>Charges</strong>"). After you have received services obtained through your use of the Service, TechCare will facilitate your payment of the applicable Charges on behalf of the Third Party Provider as such Third Party Provider’s limited payment collection agent. Payment of the Charges in such manner shall be considered the same as payment made directly by you to the Third Party Provider.</p>
<p> TechCare shall charge you a convenience fee (“<strong>Fee</strong>”) for the Services provided by TechCare to you. The Fee may be charged from you at the time of booking of services on the platform or upon the completion of service.</p>
<p> Such Charges and Fee will be inclusive of applicable taxes where required by law. Charges and Fee paid by you are final and non-refundable, unless otherwise determined by TechCare or required by the relevant Consumer Law legislation. Under the relevant Consumer Law legislation, you may be entitled to a refund for a major failure of the Services, or other remedies for a minor failure. You retain the right to request lower Charges or Fee from a Third Party Provider for services received by you from such Third Party Provider at the time you receive such services. TechCare will respond accordingly to any request from a Third Party Provider to modify the Charges for a particular service.</p>
<p> All Charges and Fee are due immediately and payment will be facilitated by TechCare using the preferred payment method designated in your Account, after which TechCare will send you a receipt by email. If your primary Account payment method is determined to be expired, invalid or otherwise not able to be charged, you agree that TechCare may, as the Third Party Provider’s limited payment collection agent, use a secondary payment method in your Account, if available.</p>
<p> As between you and TechCare, TechCare reserves the right to establish, remove and/or revise Charges for any or all services obtainable through the use of the Services at any time in TechCare’s sole discretion. Further, you acknowledge and agree that Charges and Fees applicable in certain geographical areas may increase substantially during times of high demand. TechCare will use reasonable efforts to inform you of Charges and Fees that may apply, provided that you will be responsible for Charges and Fees incurred under your Account regardless of your awareness of such Charges, Fees or the amounts thereof. TechCare may from time to time provide certain users with promotional offers and discounts that may result in different amounts charged for the same or similar services obtained through the use of the Services, and you agree that such promotional offers and discounts, unless also made available to you, shall have no bearing on your use of the Services or the Charges applied to you. You may elect to cancel your request for services from a Third Party Provider at any time prior to such Third Party Provider’s arrival, in which case you may be charged a cancellation fee. Additionally, the applicable taxes (whether direct or indirect) that are liable to be charged/ deducted on cancellation fee will charged to you by TechCare.</p>
<p> Further, TechCare may from time to time offer subscription packages to you, wherein, in exchange for monetary consideration, additional benefits such as discounted services from Third Party Providers will be made available to you. The said benefits will only be available for a limited period as may be agreed with you in advance.</p>+
<p> This payment structure is intended to fully compensate the Third Party Provider for the services provided. TechCare does not designate any portion of your payment as a tip or gratuity to the Third Party Provider. Any representation by TechCare (on TechCare’s website, in the Application, or in TechCare’s marketing materials) to the effect that tipping is "voluntary," “not required,” and/or “included” in the payments you make for services provided is not intended to suggest that TechCare provides any additional amounts, beyond those described above, to the Third Party Provider. You understand and agree that, while you are free to provide additional payment as a gratuity to any Third Party Provider who provides you with services obtained through the Service, you are under no obligation to do so. Gratuities are voluntary. After you have received services through the Service, you will have the opportunity to rate your experience and leave additional feedback about your Third Party Provider.</p>
<p> It is clarified that the Charges and Fees (respectively) shall be made only for the services provided by the Third Party Provider to you and for the Services provided by TechCare to you.</p>
<p> <strong>5. DISCLAIMERS; LIMITATION OF LIABILITY; INDEMNITY.</strong></p>
<p> <strong>LIMITATION SUBJECT TO LOCAL CONSUMER LAW</strong></p>
<p> The limitations and disclaimer in this section 5 do not purport to limit liability or alter your rights as a consumer that cannot be excluded under applicable law, including the relevant consumer law legislation.</p>
<p> <strong>DISCLAIMER.</strong></p>
<p> Except as required of TechCare under the consumer guarantees, the services are provided "as is" and “as available.” TechCare disclaims all representations and warranties, express, implied or statutory, not expressly set out in these terms, including any implied warranties of merchantability, fitness for a particular purpose and non-infringement, and makes no representation, warranty, or guarantee regarding the reliability, timeliness, quality, suitability or availability of the services or any services requested through the use of the services, or that the services will be uninterrupted or error-free. TechCare does not guarantee the quality, suitability, safety or ability of third party providers. You agree that the entire risk arising out of your use of the services, and any service or good requested in connection therewith, remains solely with you, to the maximum extent permitted under applicable law, including the relevant consumer law legislation.</p>
<p> <strong>LIMITATION OF LIABILITY.</strong></p>
<p> If you are acquiring the services as a consumer, TechCare's liability for a failure to comply with a consumer guarantee is limited to: in the case of services supplied to you as part of the services under this agreement, the supply of the relevant services again, or the payment of the cost of resupplying the services.</p>
<p> TechCare's liability to you for a breach of any condition, warranty or term of this agreement that is not a breach of a consumer guarantee is limited in the following way: TechCare shall not be liable for indirect, incidental, special, exemplary, punitive or consequential damages, including lost profits, lost data, personal injury or property damage related to, in connection with, or otherwise resulting from any use of the services, even if TechCare has been advised of the possibility of such damages. TechCare shall not be liable for any damages, liability or losses arising out of: (i) your use of or reliance on the services or your inability to access or use the services; or (ii) any transaction or relationship between you and any third party provider, even if TechCare has been advised of the possibility of such damages. TechCare shall not be liable for delay or failure in performance resulting from causes beyond TechCare's reasonable control. in no event shall TechCare's total liability to you in connection with the services for all damages, losses and causes of action exceed rupees then thousand (inr 10,000).</p>
<p> TechCare’S services may be used by you to request and schedule home-based services with third party providers, but you agree that TechCare  has no responsibility or liability to you related to any home-based services provided to you by third party providers other than as expressly set forth in these terms.</p>
<p> TechCare will maintain a complaints management framework, and will manage this framework on behalf of third party providers, in a reasonable way and in accordance with the non-excludable requirements of the relevant consumer law legislation.</p>
<p> Notwithstanding anything contained in these terms, TechCare will not be deemed to be in default or be responsible for delays or failures in performance resulting from acts beyond the reasonable control of TechCare. such acts shall include but not be limited to acts of god, riots, acts of war, epidemics, pandemics, trade embargoes, fire, typhoons, earthquakes, other natural disasters. etc.</p>
<p> The limitations and disclaimer in this section 5 do not purport to limit liability or alter your rights as a consumer that cannot be excluded under applicable law, including any of the non-excludable requirements of the relevant consumer law legislation.</p>
<p> <strong>Indemnity.</strong></p>
<p> You agree to indemnify and hold TechCare and its affiliates and their officers, directors, employees and agents harmless from any and all claims, demands, losses, liabilities, and expenses (including attorneys’ fees) arising out of or in connection with: (i) your use of the Services or services or goods obtained through your use of the services; (ii) your breach or violation of any of these Terms; (iii) TechCare’s use of your User Content; or (iv) your violation of the rights of any third party,including Third Party Providers (<em>"</em><strong>Losses</strong> <em>"</em>).</p>
<p> Your liability under this clause shall be reduced proportionately if, and to the extent that, TechCare directly caused or contributed to any such Losses</p>
<p> <strong>6. GOVERNING LAW; ARBITRATION.</strong></p>
<p> There are a number of mechanisms available to you to resolve any dispute, conflict, claim or controversy arising out of or broadly in connection with or relating to the Services or these Terms, including those relating to its validity, its construction or its enforceability or with the services provided by a Third Party Provider (any "<strong>Dispute</strong>"). TechCare or its affiliates operate a complaints process to allow you to make complaints about TechCare or Third Party Providers, and TechCare or its affiliates also manage refunds to you in relation to those complaints. TechCare or its affiliates will operate this complaints process in a reasonable manner. You agree and acknowledge that you must raise any Dispute with the Services or the services provided by a Third Party Provider as soon as is practicable, but no later than 48 hours from the time the Dispute arises. If you fail to raise a Dispute within 48 hours from the initial occurrence of such Dispute, TechCare shall be under no obligation to resolve such Dispute. If a Dispute is reported more than 48 hours after the initial occurrence of the Dispute TechCare shall in its sole discretion choose whether or not to attempt resolution of the Dispute.</p>
<p> In addition, you may have rights to make a complaint to fair trading or consumer law bodies in relation to applicable consumer laws, including the non-excludable portions of the relevant Consumer Law legislation.</p>
<p> Except as otherwise set forth in these Terms, these Terms shall be exclusively governed by and construed in accordance with the laws of India, excluding its rules on conflicts of laws. The Vienna Convention on the International Sale of Goods of 1980 (CISG) shall not apply. In the event of a Dispute, either party may file an action in the courts of India or pursue final and binding arbitration or other alternative dispute resolution as agreed upon by the parties. If either party elects to pursue final and binding arbitration, the venue of the arbitration shall be New Delhi, India.</p>
<p> Any proceedings, including documents and briefs submitted by the parties, correspondence from a mediator, and correspondence, order and awards issued by an arbitrator, shall remain strictly confidential and shall not be disclosed to any third party without the express written consent from the other party unless: (i) the disclosure to the third party is reasonably required in the context of conducting the mediation or arbitration proceedings; and (ii) the third party agrees unconditionally in writing to be bound by the confidentiality obligation set out in these Terms.</p>
<p> <strong>7. Other Provisions</strong></p>
<p> Claims of Copyright Infringement.</p>
<p> Claims of copyright infringement should be sent to grievanceofficer@techcare.com.</p>
<p> Grievance Officer.</p>
<p> For the purposes of Consumer Protection Act, 2019 and rules and regulations thereunder, the grievance officer of TechCare shall be:</p>
<p> Mr. Makrand Bhonde</p>
<p> TechCare Technologies India Private Limited</p>
<p> E-mail: <a href="mailto:grievanceofficer@techcare.com"> grievanceofficer@techcare.com </a></p>
<p> Phone: +91<strong> </strong>124 457 0250</p>
<p> Timings: 10 AM – 5 PM, Monday-Friday, excluding public holidays.</p>
<p> Notice.</p>
<p> TechCare may give notice by means of a general notice on the Services, electronic mail to your email address in your Account, or by written communication sent to your address as set forth in your Account. You may give notice to TechCare by written communication to TechCare's address at R-5, PNR House, Green Park Market, New Delhi- 110016.</p>
<p> General.</p>
<p> You may not assign or transfer these Terms in whole or in part without TechCare’s prior written approval. You give your approval to TechCare for it to assign or transfer these Terms in whole or in part, including to: (i) a subsidiary or affiliate; (ii) an acquirer of TechCare’s equity, business or assets; or (iii) a successor by merger. No joint venture, partnership, employment or agency relationship exists between you, TechCare or any Third Party Provider as a result of the contract between you and TechCare or use of the Services.</p>
<p> If any provision of these Terms is held to be illegal, invalid or unenforceable, in whole or in part, under any law, such provision or part thereof shall to that extent be deemed not to form part of these Terms but the legality, validity and enforceability of the other provisions in these Terms shall not be affected. In that event, the parties shall replace the illegal, invalid or unenforceable provision or part thereof with a provision or part thereof that is legal, valid and enforceable and that has, to the greatest extent possible, a similar effect as the illegal, invalid or unenforceable provision or part thereof, given the contents and purpose of these Terms. These Terms, including any incorporated policies, constitute the entire agreement and understanding of the parties with respect to its subject matter and replaces and supersedes all prior or contemporaneous agreements or undertakings regarding such subject matter. Nothing in this clause limits your rights as a consumer that cannot be excluded under applicable law, including the relevant Consumer Law legislation. In these Terms, the words “including” and “include” mean “including, but not limited to.”</p>


                </div>
                  </div>  
                  </div>  
                  </div>  
                  </div>  
                 </section>
        </>
    )
}

export default TermsConditions
